{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unitycatalog.postgresqlName" . }}
  labels:
    {{- include "unitycatalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    {{- include "unitycatalog.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
