{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "unitycatalog.pvcName" . }}
  labels:
    {{- include "unitycatalog.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- toYaml .Values.server.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | quote }}
  {{- with .Values.server.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}

