{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unitycatalog.postgresqlSecretName" . }}
  labels:
    {{- include "unitycatalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  {{ .Values.postgresql.passwordKey }}: {{ .Values.postgresql.password | quote }}
{{- end }}
