{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unitycatalog.serviceAccountName" . }}
  labels:
    {{- include "unitycatalog.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
