apiVersion: v2
name: unitycatalog
description: Unity Catalog OSS API server for mizuumi-engine
type: application
version: 0.1.0
appVersion: "v0.6.0"
home: https://github.com/unitycatalog/unitycatalog
sources:
  - https://github.com/unitycatalog/unitycatalog
