{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.name" . }}-gateway
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: https
      port: {{ .Values.gateway.service.port }}
      targetPort: https
{{- end }}
